# This file should be in the 'macro-logger-app' directory, 
# which is set as the 'Base directory' in Netlify build settings.

# 1. Redirect root of macrologger.netlify.app to its /macro-logger path (no slash)
[[redirects]]
  from = "/"
  to = "/macro-logger"
  status = 301
  force = true

# 2. Rewrite specific known static files from public dir
# Vite will still generate links like /macro-logger/favicon.ico due to base: '/macro-logger'
[[redirects]]
  from = "/macro-logger/favicon.ico"
  to = "/favicon.ico"
  status = 200
[[redirects]]
  from = "/macro-logger/apple-touch-icon.png"
  to = "/apple-touch-icon.png"
  status = 200
[[redirects]]
  from = "/macro-logger/pwa-192x192.png"
  to = "/pwa-192x192.png"
  status = 200
[[redirects]]
  from = "/macro-logger/pwa-512x512.png"
  to = "/pwa-512x512.png"
  status = 200
[[redirects]]
  from = "/macro-logger/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200
[[redirects]]
  from = "/macro-logger/registerSW.js"
  to = "/registerSW.js"
  status = 200
[[redirects]]
  from = "/macro-logger/sw.js"
  to = "/sw.js"
  status = 200
[[redirects]]
  from = "/macro-logger/workbox-*:name.:ext"
  to = "/workbox-:name.:ext"
  status = 200

# 3. Rewrite Vite's bundled assets (Vite adds the slash for /assets/)
[[redirects]]
  from = "/macro-logger/assets/*"
  to = "/assets/:splat"
  status = 200

# 4. SPA Fallback for /macro-logger and /macro-logger/*
# This rule should handle requests like /macro-logger (proxied from portfolio)
# and /macro-logger/today. React Router basename is now "/macro-logger".
[[redirects]]
  from = "/macro-logger/*"
  to = "/index.html"
  status = 200 